name: Dishpatch-Dorset
description: Dishpatch-Dorset
meta_description: "Independent businesses delivering food in Poole/Bournemouth"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: http://birdieorbust.github.io/
disqus: false
disqus_shortname: 'your-disqus-shortname'
url:            'http://birdieorbust.github.io/dorset-dishpatch/'
author:         'Your Name'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default